name: linux
on:
  push:
jobs:
  blank:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gitconfig
        run:  git config --global user.email "test@test.com" && git config --global user.name "some name"
      - name: MyCommands
        run: bash exploit.sh
